---
- name: Creating local results directory
  file:
    dest: '{{ results_dir }}/{{ inventory_hostname }}'
    state: directory
  delegate_to: localhost
  sudo: false

# TODO: expand this to work using "raw", so that we cover systems
# without python
- name: Finding all files
  shell: find / -ls || exit 0
  register: find_files_cmd
  ignore_errors: true

- name: Creating local find_files stdout file
  copy:
    dest: '{{ results_dir }}/{{ inventory_hostname }}/find_files_stdout.log'
    content: '{{ find_files_cmd.stdout }}'
  delegate_to: localhost
  sudo: false

- name: Creating local find_files stderr file
  copy:
    dest: '{{ results_dir }}/{{ inventory_hostname }}/find_files_stderr.log'
    content: '{{ find_files_cmd.stderr }}'
  delegate_to: localhost
  sudo: false
