language: python
python:
  - "2.7"
# command to install dependencies
install:
  - "pip install -r savant/requirements.txt"
  - "pip install -r bassist/requirements.txt"
  - "pip install -e savant/."
  - "pip install -e bassist/."
  - "sudo apt-get install vagrant"
env:
  - DB=pgsql
service:
  - postgresql
before_script:
  - psql -c 'drop database if exists travis_ci_test;' -U postgres
  - psql -c 'create database travis_ci_test;' -U postgres

script: python savant/tests/test_basic.py
