language: python
python:
  - "2.7"
# command to install dependencies
install:
  - "pip install -r savant/requirements.txt"
  - "pip install -r bassist/requirements.txt"
  - "pip install -e savant/."
  - "pip install -e bassist/."
env:
  - DB=pgsql
service:
  - postgresql
#before_script:
#  - psql -c 'drop database if exists travis_ci_test;' -U postgres
#  - psql -c 'create database travis_ci_test;' -U postgres
#  - psql -U postgres -d travis_ci_test -a -f savant/db_scripts/tables.sql
#  - psql -U postgres -d travis_ci_test -a -f savant/db_scripts/functions.sql
  - touch savant/app/db_config.json
  - cat savant/app/db_config_travis.json >> savant/app/db_config.json

after_deploy:
  - ls
  - curl -F file=@home/travis/build/Doveps/mono/Savant/tests/Scanner_Files/33.33.33.50/find_debs_stdout.log http://127.0.0.1:5000/doveps/api/flavor/create/
  - curl -F file=@home/travis/build/Doveps/mono/Savanttests/Scanner_Files/33.33.33.50/find_groups_stdout.log http://127.0.0.1:5000/doveps/api/flavor/create/
  - curl -F file=@home/travis/build/Doveps/mono/Savanttests/Scanner_Files/33.33.33.50/find_shadow_stdout.log http://127.0.0.1:5000/doveps/api/flavor/create/
  - curl -F file=@home/travis/build/Doveps/mono/Savanttests/Scanner_Files/33.33.33.50/find_users_stdout.log http://127.0.0.1:5000/doveps/api/flavor/create/

script:
  - docker-compose -f docker-compose.test.yml up -d
