version: '3'
services:
  db:
    image: postgres
    #restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: doveps
    expose:
      - "5432"
    volumes:
      # https://gist.github.com/onjin/2dd3cc52ef79069de1faa2dfd456c945
      - ./savant/db_scripts:/docker-entrypoint-initdb.d/
  savant:
    build: .
    command: python savant/run.py
   # command: python savant/tests/test_basic.py
    #command: bash
    expose:
      - "5000"
    volumes:
      - .:/code
    ports:
      - "5000:5000"
    depends_on:
      - db
  tests:
    build: .
    command: bash -c 'sleep 5; rm -rf savant/app/db_config.json; touch savant/app/db_config.json;  cat savant/app/db_config_travis.json >> savant/app/db_config.json; python savant/tests/test_basic.py'
    depends_on:
      - db

