
version: '3'
services:
  db:
    image: postgres
    #restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: doveps
    expose:
      - "5432"
    volumes:
      # https://gist.github.com/onjin/2dd3cc52ef79069de1faa2dfd456c945
      - ./savant/db_scripts:/docker-entrypoint-initdb.d/
  tests:
    build: .
    command: python savant/tests/test_basic.py
    depends_on:
      - db
