version: '3'
services:
  db:
    build: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: doveps
    expose:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 3
    # TODO: find a way to dev locally without needing to expose this port!
    ports:
      - "5432:5432"
  savant:
    build:
      context: .
      dockerfile: savant/Dockerfile
    depends_on:
      - db
    expose:
      - "5000"
    ports:
      - "5000:5000"
    # FOR DEBUGGING: uncomment following two (entrypoint/command) lines
    #entrypoint: ['']
    #command: ['sleep', '100000']
    # then `docker exec -it mono_savant_1 bash`
    # now you are in the built environment and can look around
    # then `python run.py`
