version: '3'
services:
  db:
    image: postgres
    #restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    expose:
      - "5432"
    ports:
      - "5432:5432"
  savant:
    build: .
    command: python savant/tests/test_basic.py
    # command: python savant/run.py
    #command: bash
    expose:
      - "5000"
    volumes:
      - .:/code
    ports:
      - "5000:5000"
    depends_on:
      - db
