# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 22:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comparison',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Diff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=250)),
                ('system', models.CharField(max_length=250)),
                ('action', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Playbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comparison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='savant.Comparison')),
                ('diffs', models.ManyToManyField(to='savant.Diff')),
            ],
        ),
        migrations.AddField(
            model_name='comparison',
            name='diffs',
            field=models.ManyToManyField(to='savant.Diff'),
        ),
    ]
