---
# TODO: expand these to work using "raw", so that we cover systems
# without python
- name: Find all running processes
  shell: ps -ef
  register: find_processes

- name: Find existing find_files scan results
  find_scan:
    hostvars: "{{ hostvars['localhost'] }}"
    of_host: '{{ inventory_hostname }}'
    key: find_files

- name: Find all files
  shell: find / -ls || exit 0
  register: find_files
  when: not scanned_find_files
