---
# Copyright (c) 2015 Kurt Yoder
# See the file LICENSE for copying permission.
# TODO: expand these to work using "raw", so that we cover systems
# without python
- name: Find all running processes
  shell: ps -eo pid,ppid,uid,gid,cgroup,f,ni,pri,tty,args -www
  register: find_processes

# TODO: this will be much improved by a custom scanner
- name: Find all files
  shell: find / -not -fstype vboxsf -not -fstype tmpfs -not -fstype devtmpfs -not -fstype proc -not -fstype sysfs -not -fstype fusectl -not -fstype debugfs -not -fstype securityfs -not -fstype pstore -not -fstype rpc_pipefs -not -fstype cgroup -ls || exit 0
  register: find_files

- name: Find installed .deb packages
  shell: dpkg -l || exit 0
  register: find_debs

- name: Find service status
  shell: service --status-all || exit 0
  register: find_service_status

- name: Find initctl list
  shell: initctl list || exit 0
  register: find_initctl_list

- name: Find users
  shell: getent passwd || exit 0
  register: find_users

- name: Find shadow
  shell: getent shadow || exit 0
  register: find_shadow

- name: Find groups
  shell: getent group || exit 0
  register: find_groups

- name: Find network interfaces
  shell: ip addr list || exit 0
  register: find_network_interfaces

- name: Find network routes
  shell: netstat -nr || exit 0
  register: find_network_routes

- name: Find network connections
  shell: netstat -nap || exit 0
  register: find_network_connections

- name: Find firewall rules
  shell: iptables-save || exit 0
  register: find_firewall_rules

- name: Find kernel version
  shell: uname -a || exit 0
  register: find_kernel_version

- name: Find kernel extensions
  shell: lsmod || exit 0
  register: find_kernel_extensions
