---
- name: Create results directories
  file:
    dest: '{{ results_dir }}/{{ item }}'
    state: directory
  with_items: groups['scanned']

- name: Create results files
  copy:
    dest: 'local/{{ item.0 }}/{{ item.1 }}_{{ item.2 }}.log'
    content: '{{ hostvars[item.0][item.1][item.2] }}'
  when: hostvars[item.0][item.1]['changed']
  with_nested:
    - groups['scanned']
    -
      - 'find_processes'
      - 'find_files'
      - 'find_debs'
      - 'find_service_status'
      - 'find_initctl_list'
      - 'find_users'
      - 'find_shadow'
      - 'find_groups'
      - 'find_network_interfaces'
      - 'find_network_routes'
      - 'find_network_connections'
      - 'find_firewall_rules'
      - 'find_kernel_version'
      - 'find_kernel_extensions'
    - ['stderr', 'stdout']

- name: Remove SSH fingerprint trust, IFF we added it
  lineinfile:
    dest: ~/.ssh/known_hosts
    line: '{{ item }}'
    state: absent
  with_items:
    ssh_keyscan_command.stdout_lines
  when:
    trust_ssh_lineinfile.changed
