# -*- mode: ruby -*-
# vi: set ft=ruby :
# Copyright (c) 2015 Kurt Yoder
# See the file LICENSE for copying permission.

$ip = '33.33.33.50'

$hostname = 'ubuntu-14-04'

$script = ''

load 'vagrant_base.rb'
