# -*- mode: ruby -*-
# vi: set ft=ruby :

$script = <<SCRIPT
echo disabling apt auto-updates
echo 'APT::Periodic::Update-Package-Lists "0";' > /etc/apt/apt.conf.d/20auto-upgrades
echo 'APT::Periodic::Unattended-Upgrade "0";' >> /etc/apt/apt.conf.d/20auto-upgrades
SCRIPT

Vagrant.configure('2') do |config|

# Plugin-specific configurations
  # Detects vagrant-cachier plugin
  if Vagrant.has_plugin?('vagrant-cachier')
    puts 'INFO:  Vagrant-cachier plugin detected. Optimizing caches.'
    config.cache.auto_detect = true
    config.cache.enable :chef
    config.cache.enable :apt
  else
    puts 'WARN:  Vagrant-cachier plugin not detected. Continuing unoptimized.'
  end

  config.vm.hostname = 'ubuntu-14-04-delta-apache2'

  config.vm.box = 'opscode-ubuntu-14.04'
  config.vm.box_url = 'http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-14.04_chef-provisionerless.box'

  config.vm.network :private_network, :ip => '33.33.33.51'

  config.vm.provider :virtualbox do |vb|
    vb.customize [
      'modifyvm', :id,
      '--memory', '256',
      '--cpus', '1',
    ]
  end

  # Enable SSH agent forwarding for git clones
  config.ssh.forward_agent = true

  # remove apt auto-updates, otherwise our VM gets into an unpredictable state
  config.vm.provision "shell", inline: $script

  config.vm.provision 'shell',
    inline: 'sudo apt-get update && sudo apt-get -y install apache2'

end
