CREATE TABLE IF NOT EXISTS Debs(
	id	SERIAL8 PRIMARY KEY,
	stat TEXT,
	name TEXT,
	version TEXT,
	architecture TEXT
);

CREATE TABLE IF NOT EXISTS Flavor(
	id SERIAL8 PRIMARY KEY,
	flavors TEXT
);

CREATE TABLE IF NOT EXISTS Ansible(
	id SERIAL8 PRIMARY KEY,
	scanned_files TEXT
);